name: Generate github pages

on:
  push: 
    branches: [ master, doc-push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: doc-push

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Generate HTML files and resources
        run: cd docs && mvn

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: target/generated-docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}