name: Generate github pages

on:
  push: 
    branches: [ master, doc-push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: doc-push

      - name: Install asciidoctor
        run: sudo apt-get install -y asciidoctor

      - name: Convert asciidoc files to html
        run: |
            find docs/ -name *.adoc -exec asciidoctor -a toc -a icons=font {} \;
            find docs/ -name *.adoc -exec rm -f {} \;

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}